import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar for CalKeep Docs. Explicit (not autogenerated) so we control
 * ordering and category labels independent of filesystem layout.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Connect calendars',
      collapsed: false,
      items: [
        'integrations/google-calendar',
        'integrations/outlook',
        'integrations/icloud-and-yahoo',
      ],
    },
    {
      type: 'category',
      label: 'Admin guide',
      collapsed: false,
      items: [
        'admin/team-management',
        'admin/security',
        'admin/branding',
      ],
    },
    'faq',
  ],
};

export default sidebars;
