import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar for CalKeep Docs. Explicit (not autogenerated) so we control
 * ordering and category labels independent of filesystem layout.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Connect calendars',
      collapsed: false,
      items: [
        'integrations/google-calendar',
        'integrations/outlook',
        'integrations/icloud-and-yahoo',
      ],
    },
    {
      type: 'category',
      label: 'Use CalKeep',
      collapsed: false,
      items: [
        'booking',
        'availability',
        'recurrence',
        'contacts',
        'tasks',
        'crm',
        'mobile',
      ],
    },
    {
      type: 'category',
      label: 'Admin guide',
      collapsed: false,
      items: [
        'admin/team-management',
        'admin/team-calendar-visibility',
        'admin/security',
        'admin/saml',
        'admin/scim',
        'admin/branding',
        'admin/platform-automation',
        'admin/api',
        'admin/webhooks',
        'admin/audit',
        'admin/compliance',
        'admin/ai-provider',
      ],
    },
    'release-posture',
    'faq',
  ],
};

export default sidebars;
